CREATE DATABASE IF NOT EXISTS vlxd_product;
USE vlxd_product;

CREATE TABLE Nhacungcap (
    Mancc VARCHAR(50) PRIMARY KEY,
    Tenncc VARCHAR(255) NOT NULL,
    Sdtncc VARCHAR(15),
    Diachincc VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE Danhmucsp (
    Madm INT PRIMARY KEY AUTO_INCREMENT,
    Tendm VARCHAR(100) NOT NULL UNIQUE,
    Mota VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE Nguyenvatlieu (
    Manvl VARCHAR(50) PRIMARY KEY,
    Tennvl VARCHAR(255) NOT NULL,
    Dvt VARCHAR(50) NOT NULL,
    Giavon DECIMAL(18, 2) DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE Sanpham (
    Masp VARCHAR(50) PRIMARY KEY,
    Tensp VARCHAR(255) NOT NULL,
    Madm INT,
    Dvt VARCHAR(50) NOT NULL,
    Giaban DECIMAL(18, 2) DEFAULT 0,
    FOREIGN KEY (Madm) REFERENCES Danhmucsp(Madm) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE Congthucsanpham (
    Masp VARCHAR(50),
    Manvl VARCHAR(50),
    Soluong DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (Masp, Manvl),
    FOREIGN KEY (Masp) REFERENCES Sanpham(Masp) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Manvl) REFERENCES Nguyenvatlieu(Manvl) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
